CREATE TABLE PRODUCT(
  ID              INT NOT NULL AUTO_INCREMENT,
  DEST_ID         INT NOT NULL,
  EMBARK_PORT_ID  INT NOT NULL,
  SHIP_ID         INT NOT NULL,
  DURATION        INT,
  SAILING_DATE    DATE,
  MAX_OCCUPANCY   INT,
  DEBARK_PORT_ID  INT NOT NULL,
  SAILING_ID      INT NOT NULL,

  PRIMARY KEY(ID),
  FOREIGN KEY(SHIP_ID) REFERENCES SHIP(ID) ON DELETE CASCADE,
  FOREIGN KEY(DEST_ID) REFERENCES DESTINATION(ID) ON DELETE CASCADE,
  FOREIGN KEY(EMBARK_PORT_ID) REFERENCES PORT(ID) ON DELETE CASCADE,
  FOREIGN KEY(DEBARK_PORT_ID) REFERENCES PORT(ID) ON DELETE CASCADE
)
  ENGINE=InnoDB
  DEFAULT CHARSET=utf8;